plugins { id 'com.android.application' }

android {
    namespace 'com.hookscale.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hookscale.app'
        minSdk 23
        targetSdk 35
        versionCode 6
        versionName '1.5'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
